# Generated by Django 6.0.2 on 2026-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_servicerequest_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
