# Generated by Django 6.0.2 on 2026-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_servicerequest_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='custom_problem',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='problem_type',
            field=models.CharField(choices=[('tyre_puncture', 'Tyre Puncture'), ('battery_dead', 'Battery Dead'), ('engine_overheat', 'Engine Overheat'), ('fuel_empty', 'Fuel Empty'), ('brake_issue', 'Brake Issue'), ('accident', 'Accident'), ('towing', 'Need Towing'), ('locked_out', 'Locked Out'), ('starting_trouble', 'Starting Trouble'), ('oil_leak', 'Oil Leak'), ('other', 'Other')], default='tyre_puncture', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('bike', 'Bike'), ('three_wheeler', 'Three Wheeler'), ('bus', 'Bus'), ('lorry', 'Lorry'), ('other', 'Other')], default='car', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
