# Generated by Django 6.0.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_approval_status_user_full_name_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
